name: Feature Request
description: Suggest an idea for OpenCUI
title: "[Feature Request]: "
labels: ["enhancement"]
  
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest an idea for OpenCUI!
        
        An important design principle of OpenCUI is approaching problems from first principle, which means we dig down first (foundation), before we build up actual thing. In general, we only consider adding new features that solve a problem that cannot be easily dealt with using existing usages (i.e. not just an alternative way of doing things that can already be done). The problem should also be common enough to justify the addition.

  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
      - label: I have searched the existing issues
        required: true
        
  - type: textarea
    attributes:
      label: Summary
      description: One paragraph explanation of the feature.
    validations:
      required: true
      
  - type: textarea
    attributes:
      label: Motivation
      description: |
        Explain your use case, context, and rationale behind this feature request. More importantly, what is the end user experience you are trying to build that led to the need for this feature?
        For example:
          Why are we doing this? 
          What use cases does it support? 
          What is the expected outcome?
    validations:
      required: true
      
  - type: textarea
    attributes:
      label: Describe alternatives you've considered
      description: |
        A clear and concise description of the alternative solutions you've considered. 
        Be sure to explain why OpenCUI's existing customizability isn't suitable for this feature.
    validations:
      required: true
      
  - type: textarea
    attributes:
      label: Additional context
      description: |
        Add any other context or screenshots about the feature request here.
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
